### PR TITLE
Updated FAQs page

### PR DESCRIPTION
**Pull request by shreyad216**

### CODE REVIEW

**Review by carboxylman — CHANGES_REQUESTED** [review]
@shreyad216 can you please resubmit this without all the needless whitespace changes?  Makes it really hard to see actual changes during review.  Thanks!

**Comment by dpemmerich** [comment]
@carboxylman - if you view the latest commit (e64a196) - it has only the changes. It's really odd that it thought the whole page was basically deleted and rewritten when she only changed that one line

**Comment by carboxylman** [comment]
> @carboxylman - if you view the latest commit ([e64a196](https://github.com/ITI/searcch/commit/e64a1961d6e76c73cb4e409bf42699e523383ded)) - it has only the changes. It's really odd that it thought the whole page was basically deleted and rewritten when she only changed that one line

It is too bad that github doesn't make this clear, but the changes include CRs, not only LFs, and those are the diffs, and that is why the whitespace diffs are still present after the recent pushes on this branch.

**Comment by shreyad216** [comment]
@carboxylman I believe it should be fixed now

**Pull request merged**
