### PR TITLE
Candidate artifacts

### PR DESCRIPTION
**Pull request by carboxylman**

### CODE REVIEW

**Comment by ckouder** [comment]
@carboxylman hello david, i tested `disable extraction` and `disable fetch` functions of the new hub-dev and they all work great! But I cannot trigger import candidates function ... Can you give me an example artifact that triggers this function? In addition, the webpage will return an error when I click `delete` after I import a new artifact: `404 Not Found: nonexistent artifact group`. I think I can work on the problem

**Comment by carboxylman** [comment]
@ckouder sure, try https://www.acsac.org/2021/program/final/s253.html (any of the ACSAC papers from 2018-2021 with artifacts will support this; just waiting for paper uploads for 2022, then that will work too).

**Comment by carboxylman** [comment]
@ckouder fixed the delete issue; many thanks!  Rebuilding on -dev now, should be just a couple more minutes.

**Comment by ckouder** [comment]
Thank you david! i tried to import the artifact https://www.acsac.org/2021/program/final/s253.html but the progress bar stops at 70% so i didn't have a chance to see the result

**Review by ckouder — APPROVED** [review]
I think this is ready to merge

**Pull request merged**
